In [4]:
import numpy as np

def createSudokuBoard():
    sudoku = np.array([[3,0,0,1],[0,1,3,2],[0,0,2,3],[0,0,0,4]])
    return sudoku

if __name__ == "__main__":
   sudoku = createSudokuBoard()
   print(sudoku)


[[3 0 0 1]
 [0 1 3 2]
 [0 0 2 3]
 [0 0 0 4]]
